### ISSUE TITLE
Hub stops responding after some time

### ISSUE THREAD

**Issue by ollie-art** [CapableRobot/CapableRobot_USBHub_Firmware#7]
I've got the hub working in part of an automated test setup.  I'm only using Port 1, and this is connecting to a UUT.

I'm using the hub to power down and power up this port using the command line commands:

usbhub power state --port 1 --off
usbhub power state --port 1 --on

every few minutes.  There's plenty of sleeps in there, so it's not trying to do one and then another really quickly.

It's working great, and a very useful tool.

However, after some time (sometimes 5 hours, other times, 24 hours) the hub seems to just freeze up.  It stops responding to commands, and times out, as in the attached example.

![hub crash](https://user-images.githubusercontent.com/81232998/112139176-5fb0a980-8bca-11eb-8a12-bd85f4e02e48.png)

The problem is resolved by power-cycling the whole hub.  Unfortunately I can't do this automatically.
In the first instance I'd be happy with a workaround. 
Happy to help try to provide more information as requested.
Best.
Ollie

**Comment by osterwood** [comment]
Ollie,

Thanks for reporting this issue.  When these host-side errors are seen, do you know if the on-board LEDs continue to work (showing new devices enumerating & dynamic power draw) or are they stuck / frozen?  

If they continue to work (A), the issue is within the USB4715 IC and the I2C bus within the Hub is okay.  If the LEDs are frozen (B), the I2C bus has been hung by a device on it and a reset is required (thought it could be performed by the MCU instead of a power cycle).

If A, a really easy work around is to update your host-side driver to the GitHub tree.  This pre-release version of the driver adds a "--disable-i2c" flag to the CLI interface which skips reading of the I2C EEPROM (with device serial number) when looking for attached Hubs.  

To install this pre-release driver, you can run 

```
pip install git+https://github.com/CapableRobot/CapableRobot_USBHub_Driver
```

If B, then this can be detected by the MCU and it can reset the I2C bus and the USB4715.  This means no power cycle is needed, but downstream USB devices will detach and re-enumerate when the USB4715 is reset.

One other things to check is this commit in the firmware:  https://github.com/CapableRobot/CapableRobot_USBHub_Firmware/commit/ff6286b40f435d46a75fb23fb3ab5a546ac54211

If your MCU firmware still has the 0.05 second delay, I would strong recommend changing to 0.1 seconds (or a bit longer).  I don't have the full story from Microchip, but it seems this longer delay after reset is required to allow the USB4715 additional time to complete some internal initialization for the I2C functionality to work as expected.

**Comment by osterwood** [comment]
Ollie,

Following up on your report.  Does the "--disable-i2c" flag of the pre-release host-side driver resolve this issue?  Let me know if you need help installing that version, or in updating the firmware of your Hub.

**Comment by ollie-art** [comment]
Hi Chris - thanks for your feedback - I've not yet had a chance to replicate the fault - will respond as soon as I've tried some of these suggestions!

**Comment by osterwood** [comment]
Understood!  No rush, just wanted to keep in touch on this issue.

Also, it's likely the Hub doesn't have the newest firmware / CircuitPython release (which is reported in the "boot_out.txt" file in the CIRCUITPY drive when the MCU port is connected to your Host.  if it's doesn't say 5.3.0, then I'd recommend updating the CircuitPython release and the firmware source -- the `usbhub_firmware.py` script in this repo helps with both of these.

**Comment by ollie-art** [comment]
Ok, so the condition occurred again, and the LEDs appear to be stuck/frozen, so I guess we're looking at B.

I've now plugged into the MCU too (I was only using the Host connection), but I'm not sure how I can trigger a reset?

I've checked and the hub *is* running the latest firmware (5.3.0).

**Comment by osterwood** [comment]
Thanks for the additional info.  To verify, after the host-side I2C error, if you disconnect (or connect) a downstream device by manually unplugging / plugging-in a cable, the LED do not change?

A log of any error messages from the MCU when this event occurs would be really useful in determining the cause and seeing if there is a way to recover without causing all of the downstream device from being forced to re-enumerate.  

To get this, you'd have to leave a serial terminal (like TeraTerm) open to the MCU COM port at 115200 baud -- to check that this is running correctly enter CTRL-C & CTRL-D a few times and you should see text along the lines of:

```
Auto-reload is on. Simply save files over USB to run them or enter REPL to disa.
code.py output:                                                                 
... booted ...                                                                  
... configuring hub ...                                                                                                      
    Hub IC has been configured                                                  
... configuring leds ...   

Unit SKU : CRxxxx                                                               
  Serial : xxxxxxxxxxxxxxxxx
```

When the I2C crash happens, there should be additional error messages which are printed to this console.  Would it be possible for you to setup a serial terminal to capture this output?

**Comment by ollie-art** [comment]
Hi - ok, when the fault occurs, unplugging/plugging in a downstream device makes no difference to the LEDs, they remain stuck/frozen.

When I plug in a USB cable into the MCU port, I don't see any additional virtual COM ports show up in Device Manager.  I get a COM port appear when I plug a USB into the Host port, and additional ones show up when I plug in downstream devices.  Plugging into the MCU port allows me to access the device like a drive, and some other drivers show up in Device Manager, though CircuitPython CDC Control and CircuitPython Audio show up in Device Manager with a problem (drivers not installed, and device cannot start respectively).  But no new COM ports to connect to :( ?

**Comment by osterwood** [comment]
The COM port when the host side is connected is the USB to serial adapter built into the USB4715 IC (the main chip inside the Hub).

On my Windows testing virtual machine, the MCU usbser driver installs correctly and doesn't need additional steps.  What Windows version are you running?

You can try forcing the driver registration via (this takes a bit longer than you'd expect it to):
```
pip install capablerobot_usbregister
usbregister register --vid 1240 --pid 60851 --iid 0 --type usbser
```

Output should look like:
```
Starting registration of (VID 1240 PID 60851)
  Assigning interface 0 to usbser driver
Registration complete
```

**Comment by ollie-art** [comment]
(I am running Windows 7 Pro, Service Pack 1)

**Comment by osterwood** [comment]
Did running the usbregister command above register the serial driver correctly?

**Comment by ollie-art** [comment]
I've just run it.  The first time I ran it, the MCU was not connected, but I did have a USB lead connected to the Host connection.  I ran the command and got the following:
![register fail](https://user-images.githubusercontent.com/81232998/113713236-fd35ce00-96de-11eb-89f0-797a2b671817.png)
I then realised that the Host USB was plugged in.  I unplugged it and re-ran the command.  It then ran successfully (as in your example).  However, plugging the USB lead into the MCU still doesn't create a new COM port.  Windows is now showing it needs to do some updates, I wonder if it's related, so I'm going to install updates and restart now...

**Comment by ollie-art** [comment]
Ok, restarted, and still I don't get a new COM port.  I've checked on another machine (Windows 10) with the same lead and that does work properly, and I used Ctrl+C and Ctrl+D to get it into the desired state.  Just for some reason this Windows 7 PC is not behaving.  It has 7 other USB devices attached and has not had a problem with any of these, I'm a bit confused.  If necessary I can set up a separate machine to connect to the MCU port and log.  That will get you the desired log file, though it would be better for me if I could get it operating correctly on the 1 machine.

**Comment by ollie-art** [comment]
I've got the unit logging now, using a 2nd machine.  I'll send you the log as soon as the fault occurs :)

**Comment by osterwood** [comment]
Thank you!  that will be most helpful in determining root cause and recovery behavior.

I'm sorry you ran into so many issues getting Windows to connect to the MCU.  Thanks for setting up the seconds machine.  

One last question - do you have any external devices connected to the rear I2C ports?

**Comment by ollie-art** [comment]
Ok, so this time the fault occurred quite quickly.
I was "logging" from the MCU port, but I have to say that I never saw any diagnostic data.  When the fault occurred, still nothing.  Only when I did a Ctrl + D did I get something that is hopefully of use:


[2021-04-06 14:51:43.774] Traceback (most recent call last):
[2021-04-06 14:51:43.779]   File "code.py", line 83, in <module>
[2021-04-06 14:51:43.785]   File "code.py", line 79, in <module>
[2021-04-06 14:51:43.785]   File "/lib/capablerobot_usbhub.py", line 509, in poll_for_host_comms
[2021-04-06 14:51:43.785]   File "/lib/capablerobot_usbhub.py", line 446, in get_memory
[2021-04-06 14:51:43.785]   File "/lib/capablerobot_usbhub.py", line 252, in _read_register
[2021-04-06 14:51:43.785]   File "/lib/capablerobot_usbhub.py", line 117, in _register_length
[2021-04-06 14:51:43.785] KeyboardInterrupt: 
[2021-04-06 14:51:43.785] 
[2021-04-06 14:51:43.785] 
[2021-04-06 14:51:43.785] 
[2021-04-06 14:51:43.785] Press any key to enter the REPL. Use CTRL-D to reload.soft reboot
[2021-04-06 14:51:45.709] 
[2021-04-06 14:51:45.709] Auto-reload is on. Simply save files over USB to run them or enter REPL to disable.
[2021-04-06 14:51:45.709] code.py output:
[2021-04-06 14:51:45.954] ... booted ...
[2021-04-06 14:51:45.987] ... configuring hub ...
[2021-04-06 14:51:45.987]     Default configuration
[2021-04-06 14:51:45.987]     Hub IC has been configured
[2021-04-06 14:51:45.987] ... configuring leds ...
[2021-04-06 14:51:45.990] 
[2021-04-06 14:51:45.995] Unit SKU : CRZRYC
[2021-04-06 14:51:45.995]   Serial : 801F12FFFE3CA4A4
[2021-04-06 14:51:45.998] 
[2021-04-06 15:28:02.331] Traceback (most recent call last):
[2021-04-06 15:28:02.331]   File "code.py", line 132, in <module>
[2021-04-06 15:28:02.336]   File "/lib/capablerobot_usbhub.py", line 708, in power_state
[2021-04-06 15:28:02.336]   File "/lib/capablerobot_usbhub.py", line 275, in _read_register
[2021-04-06 15:28:02.336]   File "/lib/capablerobot_usbhub.py", line 275, in _read_register
[2021-04-06 15:28:02.336]   File "/lib/adafruit_bus_device/i2c_device.py", line 126, in write_then_readinto
[2021-04-06 15:28:02.336] KeyboardInterrupt: 
[2021-04-06 15:28:02.336] 
[2021-04-06 15:28:02.336] 
[2021-04-06 15:28:02.336] 
[2021-04-06 15:28:02.336] Press any key to enter the REPL. Use CTRL-D to reload.soft reboot
[2021-04-06 15:28:03.689] 
[2021-04-06 15:28:03.689] Auto-reload is on. Simply save files over USB to run them or enter REPL to disable.
[2021-04-06 15:28:03.689] code.py output:
[2021-04-06 15:28:03.934] ... booted ...
[2021-04-06 15:28:03.969] ... configuring hub ...
[2021-04-06 15:28:03.969]     Default configuration
[2021-04-06 15:28:03.969]     Hub IC is in default state
[2021-04-06 15:28:03.969]     Resetting and configuring Hub IC
[2021-04-06 15:28:04.222] ... configuring leds ...
[2021-04-06 15:28:04.230] 
[2021-04-06 15:28:04.235] Unit SKU : CRZRYC
[2021-04-06 15:28:04.238]   Serial : 801F12FFFE3CA4A4
[2021-04-06 15:28:04.238] 
[2021-04-07 15:28:39.382] Traceback (most recent call last):
[2021-04-07 15:28:39.385]   File "code.py", line 99, in <module>
[2021-04-07 15:28:39.391]   File "/lib/capablerobot_usbhub.py", line 667, in data_state
[2021-04-07 15:28:39.391]   File "/lib/capablerobot_usbhub.py", line 658, in _read_mcp_register
[2021-04-07 15:28:39.391] KeyboardInterrupt: 
[2021-04-07 15:28:39.391] 
[2021-04-07 15:28:39.391] 
[2021-04-07 15:28:39.391] 
[2021-04-07 15:28:39.391] Press any key to enter the REPL. Use CTRL-D to reload.
[2021-04-07 15:29:04.616] Adafruit CircuitPython 5.3.0 on 2020-04-29; Capable Robot Programmable USB Hub with samd51g19
[2021-04-07 15:29:04.616] >>> 
[2021-04-07 15:29:09.038] >>> 
[2021-04-07 15:29:09.764] >>> 
[2021-04-07 15:29:21.420] soft reboot
[2021-04-07 15:29:21.825] 
[2021-04-07 15:29:21.825] Auto-reload is on. Simply save files over USB to run them or enter REPL to disable.
[2021-04-07 15:29:21.825] code.py output:
[2021-04-07 15:29:22.071] ... booted ...
[2021-04-07 15:29:22.078] Traceback (most recent call last):
[2021-04-07 15:29:22.078]   File "code.py", line 34, in <module>
[2021-04-07 15:29:22.078] RuntimeError: SDA or SCL needs a pull up
[2021-04-07 15:29:22.078] 
[2021-04-07 15:29:22.078] 
[2021-04-07 15:29:22.078] 
[2021-04-07 15:29:22.078] Press any key to enter the REPL. Use CTRL-D to reload.soft reboot
[2021-04-07 15:29:59.526] 
[2021-04-07 15:29:59.526] Auto-reload is on. Simply save files over USB to run them or enter REPL to disable.
[2021-04-07 15:29:59.526] code.py output:
[2021-04-07 15:29:59.770] ... booted ...
[2021-04-07 15:29:59.775] Traceback (most recent call last):
[2021-04-07 15:29:59.775]   File "code.py", line 34, in <module>
[2021-04-07 15:29:59.775] RuntimeError: SDA or SCL needs a pull up
[2021-04-07 15:29:59.775] 
[2021-04-07 15:29:59.775] 
[2021-04-07 15:29:59.775] 
[2021-04-07 15:29:59.775] Press any key to enter the REPL. Use CTRL-D to reload.soft reboot
[2021-04-07 15:31:53.221] 
[2021-04-07 15:31:53.221] Auto-reload is on. Simply save files over USB to run them or enter REPL to disable.
[2021-04-07 15:31:53.222] code.py output:
[2021-04-07 15:31:53.492] ... booted ...
[2021-04-07 15:31:53.492] Traceback (most recent call last):
[2021-04-07 15:31:53.492]   File "code.py", line 34, in <module>
[2021-04-07 15:31:53.492] RuntimeError: SDA or SCL needs a pull up
[2021-04-07 15:31:53.492] 
[2021-04-07 15:31:53.492] 
[2021-04-07 15:31:53.492] 
[2021-04-07 15:31:53.492] Press any key to enter the REPL. Use CTRL-D to reload. 

Were you expecting some diagnostic data to be logged?  How come I'm not seeing anything?  Do I need to set it into a different mode or anything?

**Comment by ollie-art** [comment]
(And no, I don't have anything connected to the I2C ports.)

**Comment by ollie-art** [comment]
It's worth noting that the Ctrl + D didn't reset the device, and it's remained in the fault condition state.

**Comment by osterwood** [comment]
The "SCL / SDA needs a pull-up" line is strongly indicative of the USB4715 having too short a delay after reset before I2C traffic resumes -- but based on line numbers of capablerobot_usb.py, I think you already have this commit applied : https://github.com/CapableRobot/CapableRobot_USBHub_Firmware/commit/ff6286b40f435d46a75fb23fb3ab5a546ac54211

Perhaps that delay is too short for the silicon in your particular Hub.  I never did get a full explanation from Microchip on why this delay is needed, or why it needed to be longer than the datasheet species.

I'd love to get your Hub back here for a deeper dive.  Can you email support@capablerobot.com with your shipping information and we'll get a new Hub and return shipping label out to you.  Thanks so much setting up the log.

Prior to that arriving, have you tried running with the "--disable-i2c" flag from the pre-release host-side driver?  Even though the MCU isn't behaving as expected (due the I2C bus being in a strange state) that would allow your host-side software to continue to enable and disable port power.

Alternatively, you could try increase the delay in the `attach()` function to 0.5 seconds -- that was the delay that Microchip initially suggested before saying that 100ms should be sufficient.

**Comment by ollie-art** [comment]
Ok, I've emailed support with my details.  In the meantime I'll have a stab at your other suggestions...

**Comment by ollie-art** [comment]
Hi Chris - I performed the pre-release update, which seemed to go smoothly, and have been running the hub without incident so far... fingers crossed?!

**Comment by ollie-art** [comment]
Ok, the problem just reoccurred.
I was going to attempt to change the attach() function in the capablerobot_usbhub.py file in the lib directory on the MCU port (I assume this is what you meant).  However, I'm seeing this:

    def attach(self):
        ## 0xAA 0x55 : Exit SOC_CONFIG and Enter HUB_CONFIG stage
        ## 0xAA 0x56 : Exit SOC_CONFIG and Enter HUB_CONFIG stage with SMBus slave enabled
        out = [0xAA, 0x56, 0x00]

        with self.i2c_device as i2c:
            i2c.write(bytearray(out))

and I'm not seeing any delay in there at all??  What do I need to change?
(Also, just to confirm - when I installed the pre-release host-side driver, I didn't need to do anything else?  I don't for example need to enter "--disable-i2c" anywhere myself?)

**Comment by osterwood** [comment]
My mistake -- the sleep call is in the `configure(self, **opts)` method, after it calls `attach()`.

The pre-release driver adds the new "--disable-i2c" flag.  But, the default behavior is identical to the release driver -- to skip ID probing via I2C, you do need to add the flag when you invoke the `usbhub` CLI tool

**Comment by ollie-art** [comment]
Um, normally I'm using the command line commands:
usbhub power state --port 1 --off
usbhub power state --port 1 --on

I just tried:
usbhub --disable-i2c power state --port 1 --on
usbhub power state --port 1 --on --disable-i2c
usbhub --disable-i2c

and each time it tells me there is "no such option: --disable-i2c"
What am I doing wrong?

**Comment by osterwood** [comment]
I suspect an old version of the the driver is still on your system and is being used instead of the pre-release one.

I would try running `pip uninstall capablerobot_usbhub` until your system doesn't have the `usbhub` tool anymore.  Then `pip install git+https://github.com/CapableRobot/CapableRobot_USBHub_Driver` again

![Screen Shot 2021-04-13 at 3 46 21 PM](https://user-images.githubusercontent.com/10534/114612055-a34d7f00-9c6f-11eb-8dc0-e14ecc3c3917.png)

**Comment by ollie-art** [comment]
Ok, I'll do this next.  In the meantime, I've increased the sleep from 0.1 to 0.5, and ran, but if anything, this has made it worse, it fell over within about 20 minutes.

**Comment by ollie-art** [comment]
Actually - my previous comment was inaccurate - the unit did not crash after I made the change to the sleep to 0.5.  However, I've now reverted it to 0.1 and I'm now running with the --disable-i2c flag (thanks for the info, not sure why it didn't work the first time!)

**Comment by ollie-art** [comment]
The hub has been working for over 24 hours now with no faults occurring - this is a good sign!  I'll leave it a few more days and report back then, but it looks like the --disable-i2c flag may have done the trick.

**Comment by ollie-art** [comment]
Yep, looks like this has resolved the issue - not seen any repeats!

**Comment by ollie-art** [comment]
Many thanks for your help!
